const { createHash } = require('node:crypto');

const iconFonts = ['font_1749284_5i9bdhy70f8', 'font_1736178_k526ubmyhba'];

hexo.extend.filter.register('after_render:html', function prepareFirstPaint(html) {
  const root = hexo.config.root.replace(/\/?$/, '/');
  for (const font of iconFonts) {
    html = html.replaceAll('//at.alicdn.com/t/c/' + font + '.css', root + 'vendor/iconfont/' + font + '.css');
  }

  if (html.includes('<body class="home-page">')) {
    const cover = html.match(/<div id="banner"[^>]*style="background: url\(([^)]+)\)/);
    if (cover) {
      const url = cover[1].trim().replace(/^(['"])(.*)\1$/, '$2');
      html = html.replace('<head>', '<head>\n<link rel="preload" as="image" fetchpriority="high" href="' + url + '">');
    }
  }
  return html;
}, 50);

async function readRoute(path) {
  const chunks = [];
  for await (const chunk of hexo.route.get(path)) chunks.push(Buffer.from(chunk));
  return Buffer.concat(chunks);
}

// Hash the final generated bytes, including theme CSS compiled from configuration.
// Keep stable versions for unchanged assets and never rely on a manually bumped date.
hexo.extend.filter.register('after_generate', async function versionPageAssets() {
  const root = hexo.config.root.replace(/\/?$/, '/');
  const routes = hexo.route.list();
  const versions = new Map();
  await Promise.all(routes.filter((path) => /\.(css|js)$/.test(path)).map(async (path) => {
    const contents = await readRoute(path);
    versions.set(root + path, createHash('sha256').update(contents).digest('hex').slice(0, 12));
  }));

  await Promise.all(routes.filter((path) => path.endsWith('.html')).map(async (path) => {
    const html = (await readRoute(path)).toString('utf8');
    const versioned = html.replace(/<(?:link|script)\b[^>]*>/g, (element) =>
      element.replace(/\b(href|src)="([^"?#]+)(?:\?([^"#]*))?(#[^"]*)?"/g, (tag, attr, url, query = '', fragment = '') => {
        if (!url.startsWith(root)) return tag;
        const version = versions.get(decodeURI(url));
        if (!version) return tag;
        const params = new URLSearchParams(query.replaceAll('&amp;', '&'));
        params.set('v', version);
        return attr + '="' + url + '?' + params.toString().replaceAll('&', '&amp;') + fragment + '"';
      })
    );
    if (versioned !== html) hexo.route.set(path, versioned);
  }));
}, 100);
